draw_set_valign(fa_bottom)
draw_set_color(c_white)
draw_set_halign(fa_left)
draw_set_font(fnt_pixel)
var pos = getMouseCoords()
draw_text(20, global.gridData.rH - 20, "Mouse At: ["+string(pos.x)+","+string(pos.y)+"]!")